name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_deploy_prod_job:
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    name: Build and Deploy Prod Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Build And Deploy Prod
        id: builddeployprod
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_CONFORMANCE_RULES_EDITOR_PROD }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          production_branch: "main"
          app_location: "/"
          api_location: "/api"
          output_location: "build"
        env:
          NPM_CONFIG_LEGACY_PEER_DEPS: true

  build_and_deploy_preview:
    if: (github.event_name == 'pull_request' && github.event.action != 'closed') || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    name: Build and Deploy Preview
    outputs:
      preview_url: ${{ steps.builddeploypreview.outputs.static_web_app_url }}  # Capture Preview URL
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          ref: ${{ github.head_ref || github.ref_name }}
      - name: Use preview config for PR
        run: |
          cp staticwebapp.preview.config.json staticwebapp.config.json
          echo "Using preview configuration for this deployment"
      - name: Build And Deploy Preview
        id: builddeploypreview
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_CONFORMANCE_RULES_EDITOR_PROD }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/"
          api_location: "/api"
          output_location: "build"
          config_file_location: "/"
          production_branch: ${{ github.ref_name }}

  test_rule_editor_job:
    needs: build_and_deploy_preview
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    name: Test Rule Editor on Preview
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          pip install selenium webdriver-manager

      - name: Run Selenium Test on Preview
        env:
          RULE_EDITOR_URL: ${{ needs.build_and_deploy_preview.outputs.preview_url }}
        run: |
          echo "Testing on Preview Deployment: $RULE_EDITOR_URL"
          python test_rule_editor.py

  build_and_deploy_training_job:
    if: github.ref_name == 'main' && (github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed') || github.event_name == 'workflow_dispatch')
    runs-on: ubuntu-latest
    name: Build and Deploy Training Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Build And Deploy Training
        id: builddeploytraining
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_CONFORMANCE_RULES_EDITOR_TRAINING }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/"
          api_location: "/api"
          output_location: "build"
        env:
          NPM_CONFIG_LEGACY_PEER_DEPS: true

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_CONFORMANCE_RULES_EDITOR_PROD }}
          action: "close"