name: Move Issues and Pull Requests into the correct columns

# COLUMNS:
# Opened
# Assigned
# In progress (Manual)
# Ready for review
# Reviewer approved
# Closed

on:
  issues:
    types: [opened, assigned, ready_for_review, closed]
  pull_request:
    types: [ready_for_review, closed]
  pull_request_review:
    types: [submitted]

jobs:
  opened-opened:
    if: github.event.action == 'opened'
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@v0.8.1
        with:
          project: Conformance Rules Editor
          column: Opened
          repo-token: ${{ secrets.GHPROJECT_TOKEN }}
  assigned-assigned:
    if: github.event.action == 'assigned'
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@v0.8.1
        with:
          project: Conformance Rules Editor
          column: Assigned
          repo-token: ${{ secrets.GHPROJECT_TOKEN }}
  ready_for_review-ready_for_review:
    if: github.event.action == 'ready_for_review'
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@v0.8.1
        with:
          project: Conformance Rules Editor
          column: Ready for review
          repo-token: ${{ secrets.GHPROJECT_TOKEN }}
  approved-reviewer_approved:
    if: github.event.action == 'submitted' && github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@v0.8.1
        with:
          project: Conformance Rules Editor
          column: Reviewer approved
          repo-token: ${{ secrets.GHPROJECT_TOKEN }}
  closed-closed:
    if: github.event.action == 'closed'
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@v0.8.1
        with:
          project: Conformance Rules Editor
          column: Closed
          repo-token: ${{ secrets.GHPROJECT_TOKEN }}
